import React, { useState } from "react";
import { Routes, Route, useLocation, Navigate } from "react-router-dom";
import Sidebar from "./components/Sidebar";
import Navbar from "./components/Navbar";
import Dashboard from "./pages/Dashboard";
import LiveMapPage from "./pages/LiveMapPage";
import SOSRequestsPage from "./pages/SOSRequestsPage";
import RescueTeamsPage from "./pages/RescueTeamsPage";
import RegisterRescueTeamPage from "./pages/RegisterRescueTeamPage";
import RescueTeamPortal from "./pages/RescueTeamPortal";
import CitizenDashboard from "./pages/CitizenDashboard";
import TrackRescueTeam from "./pages/TrackRescueTeam";
import SheltersPage from "./pages/SheltersPage"; import ResourcesPage from "./pages/ResourcesPage"; import VolunteersPage from "./pages/VolunteersPage"; import HospitalsPage from "./pages/HospitalsPage"; import NotificationsPage from "./pages/NotificationsPage"; import WeatherPage from "./pages/WeatherPage"; import AnalyticsPage from "./pages/AnalyticsPage"; import ReportsPage from "./pages/ReportsPage"; import SettingsPage from "./pages/SettingsPage"; import LoginPage from "./pages/LoginPage"; import CitizenRegisterPage from "./pages/CitizenRegisterPage";
import ProtectedRoute from "./context/ProtectedRoute"; import { useAuth } from "./context/AuthContext"; import { navItems } from "./data/mockData";
export default function App(){const [sidebarOpen,setSidebarOpen]=useState(false);const location=useLocation();const {user}=useAuth();if(location.pathname==="/login")return <LoginPage/>;if(location.pathname==="/register")return <CitizenRegisterPage/>;const citizen=user?.role==="Citizen";const rescue=user?.role==="RescueTeam";if(citizen && !["/citizen","/track-rescue"].some(x=>location.pathname.startsWith(x)))return <Navigate to="/citizen" replace/>;if(rescue && !location.pathname.startsWith("/rescue-team-portal"))return <Navigate to="/rescue-team-portal" replace/>;const current=navItems.find(i=>i.path===location.pathname);const title=current?.label||"SDRP";return <Routes><Route element={<ProtectedRoute/>}><Route path="/citizen" element={<CitizenDashboard/>}/><Route path="/track-rescue/latest" element={<TrackRescueTeam/>}/><Route path="/track-rescue/:sosId" element={<TrackRescueTeam/>}/><Route path="/rescue-team-portal" element={<RescueTeamPortal/>}/><Route path="*" element={<div className="min-h-screen flex bg-[#eef8ef] text-[#18352a]"><Sidebar navItems={navItems} open={sidebarOpen} onClose={()=>setSidebarOpen(false)}/><div className="flex-1 min-w-0 flex flex-col"><Navbar onMenuClick={()=>setSidebarOpen(true)} title={title} subtitle="District Emergency Management Dashboard"/><main className="flex-1 min-w-0 p-4 sm:p-6 lg:p-8"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/map" element={<LiveMapPage/>}/><Route path="/sos" element={<SOSRequestsPage/>}/><Route path="/teams" element={<RescueTeamsPage/>}/><Route path="/teams/register" element={<RegisterRescueTeamPage/>}/><Route path="/shelters" element={<SheltersPage/>}/><Route path="/resources" element={<ResourcesPage/>}/><Route path="/volunteers" element={<VolunteersPage/>}/><Route path="/hospitals" element={<HospitalsPage/>}/><Route path="/notifications" element={<NotificationsPage/>}/><Route path="/weather" element={<WeatherPage/>}/><Route path="/analytics" element={<AnalyticsPage/>}/><Route path="/reports" element={<ReportsPage/>}/><Route path="/settings" element={<SettingsPage/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></main></div></div>}/></Route></Routes>}
