import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import PageHeader from "../components/PageHeader";
import { fetchMySOS, createSOSRequest } from "../services/api";

export default function CitizenDashboard(){
 const [sos,setSos]=useState([]); const [form,setForm]=useState({disasterType:"Medical",severity:"High",description:"",peopleAffected:1}); const [sending,setSending]=useState(false); const [error,setError]=useState(""); const nav=useNavigate();
 const load=()=>fetchMySOS().then(setSos).catch(()=>setSos([])); useEffect(()=>{load()},[]);
 const send=async()=>{setError("");setSending(true);try{if(!navigator.geolocation)throw new Error("GPS is not supported by this browser.");navigator.geolocation.getCurrentPosition(async pos=>{try{const location={latitude:pos.coords.latitude,longitude:pos.coords.longitude};await createSOSRequest({...form,location});setForm(v=>({...v,description:""}));await load();}catch(e){setError(e?.response?.data?.message||e.message)}finally{setSending(false)}},e=>{setError(e.message||"Location permission is required to send an SOS");setSending(false)},{enableHighAccuracy:true,timeout:15000,maximumAge:5000});}catch(e){setError(e.message);setSending(false)}};
 return <div><PageHeader title="Citizen Emergency Portal" subtitle="Send SOS, monitor response, and track your assigned rescue team."/><div className="grid lg:grid-cols-3 gap-5"><section className="lg:col-span-2 bg-white border border-[#dbeadb] rounded-2xl p-6"><div className="text-lg font-extrabold text-[#18352a]">🚨 Send Emergency SOS</div>{error&&<div className="my-3 p-3 rounded-lg bg-red-50 text-red-700 text-sm">{error}</div>}<div className="grid sm:grid-cols-2 gap-4 mt-4"><label className="text-sm font-semibold">Emergency Type<select value={form.disasterType} onChange={e=>setForm(v=>({...v,disasterType:e.target.value}))} className="mt-1.5 w-full"><option>Medical</option><option>Fire</option><option>Flood</option><option>Earthquake</option><option>Accident</option><option>Landslide</option><option>Cyclone</option><option>Other</option></select></label><label className="text-sm font-semibold">Severity<select value={form.severity} onChange={e=>setForm(v=>({...v,severity:e.target.value}))} className="mt-1.5 w-full"><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></label><label className="sm:col-span-2 text-sm font-semibold">Description<textarea value={form.description} onChange={e=>setForm(v=>({...v,description:e.target.value}))} required className="mt-1.5 w-full" rows="3" placeholder="Tell the response team what happened..."/></label></div><button onClick={send} disabled={sending} className="mt-5 w-full py-4 rounded-xl bg-red-600 text-white font-extrabold text-lg disabled:opacity-60">{sending?"Detecting location & sending...":"SEND SOS"}</button></section><section className="bg-white border border-[#dbeadb] rounded-2xl p-6"><div className="font-extrabold text-[#18352a]">My Active SOS</div><div className="mt-4 space-y-3">{sos.filter(x=>x.isActive!==false).slice(0,5).map(x=><div key={x._id||x.id} className="border rounded-xl p-4"><div className="flex justify-between"><b>{x._id?.slice(-8)||x.id}</b><span className="text-xs font-bold">{x.status}</span></div><p className="text-sm text-slate-500 mt-1">{x.disasterType} · {x.severity}</p>{x.assignedRescueTeam&&<button onClick={()=>nav(`/track-rescue/${x._id}`)} className="mt-3 w-full py-2 rounded-lg bg-green-700 text-white text-sm font-bold">Track Rescue Team</button>}</div>)}{!sos.length&&<p className="text-sm text-slate-500">No SOS requests yet.</p>}</div></section></div></div>
}
