import React, { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import PageHeader from '../components/PageHeader'
import { fetchDamageReports } from '../services/aiDamage'
import { damageReports as mockReports } from '../data/mockData'

const severityStyle = {
  High: { background: '#fbe7e4', color: '#dc4b3e' },
  Medium: { background: '#fbf0dd', color: '#d98a1f' },
  Low: { background: '#e4f4e9', color: '#2f8a52' }
}

export default function ReportsPage() {
  const [reports, setReports] = useState(mockReports)
  const [selected, setSelected] = useState(null)

  useEffect(() => {
    fetchDamageReports().then((data) => setReports(Array.isArray(data) && data.length ? data : mockReports))
  }, [])

  return (
    <div>
      <PageHeader title="AI Damage Reports" subtitle="Generated by the FastAPI + YOLO detection service" />
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {reports.map((r, i) => (
          <motion.div
            key={r.title + i}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.06 }}
            onClick={() => setSelected(r)}
            role="button"
            tabIndex={0}
            onKeyDown={(e) => e.key === "Enter" && setSelected(r)}
            className="card p-5 bg-white border border-[#dbeadb] rounded-2xl cursor-pointer hover:shadow-md transition"
          >
            <div className="w-full h-28 rounded-lg bg-[#dceadd] flex items-center justify-center text-3xl mb-3">
              🌊
            </div>
            <div className="font-bold text-forest-900">{r.title}</div>
            <div className="text-xs text-[#7d9285] mt-0.5">{r.location}</div>
            <div className="flex items-center justify-between mt-3 text-sm">
              <span className="text-[#4d6156]">Confidence: {r.confidence}</span>
              <span className="text-[11px] font-bold px-2.5 py-0.5 rounded-full" style={severityStyle[r.severity]}>
                {r.severity}
              </span>
            </div>
            <div className="text-[11px] text-[#7d9285] mt-2 font-mono">{r.detectedAt}</div>
          </motion.div>
        ))}
      </div>
      {selected && (
        <div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4" onClick={() => setSelected(null)}>
          <div className="bg-white rounded-2xl p-6 w-full max-w-md" onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-4"><h3 className="text-lg font-bold text-forest-900">Damage Report</h3><button onClick={() => setSelected(null)} className="text-xl">×</button></div>
            <div className="space-y-2 text-sm text-[#4d6156]">
              <p><b className="text-forest-900">Detection:</b> {selected.title}</p>
              <p><b className="text-forest-900">Location:</b> {selected.location || "—"}</p>
              <p><b className="text-forest-900">Confidence:</b> {selected.confidence || "—"}</p>
              <p><b className="text-forest-900">Severity:</b> {selected.severity || "—"}</p>
              <p><b className="text-forest-900">Detected:</b> {selected.detectedAt || "—"}</p>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
