import React, { useEffect, useState } from "react";
import PageHeader from "../components/PageHeader";
import { fetchSOSRequests, fetchRescueTeams, assignRescueTeam } from "../services/api";
import { onRescueAssignment, onRescueStatusUpdate, onNewSOS, joinLiveMap } from "../services/socket";

const styles={Pending:"bg-red-50 text-red-700",Dispatched:"bg-amber-50 text-amber-700","Rescue On Way":"bg-blue-50 text-blue-700",Reached:"bg-green-50 text-green-700",Resolved:"bg-emerald-50 text-emerald-700"};
const distanceKm=(a,b)=>{if(!a||!b)return null;const R=6371,dLat=(Number(b.latitude)-Number(a.latitude))*Math.PI/180,dLon=(Number(b.longitude)-Number(a.longitude))*Math.PI/180;const x=Math.sin(dLat/2)**2+Math.cos(Number(a.latitude)*Math.PI/180)*Math.cos(Number(b.latitude)*Math.PI/180)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));};
const distanceText=(d)=>d==null?"GPS unavailable":d<1?`${Math.round(d*1000)} m`:`${d.toFixed(2)} km`;

export default function SOSRequestsPage(){
 const [requests,setRequests]=useState([]);const [teams,setTeams]=useState([]);const [selected,setSelected]=useState(null);const [teamIds,setTeamIds]=useState([]);const [filter,setFilter]=useState("All");const [error,setError]=useState("");
 const load=async()=>{try{setError("");const [s,t]=await Promise.all([fetchSOSRequests(),fetchRescueTeams()]);setRequests(s);setTeams(t)}catch(e){setError(e?.response?.data?.message||"Unable to load live SOS/team data")}};
 useEffect(()=>{load();joinLiveMap();const a=onRescueAssignment(load),b=onRescueStatusUpdate(load),c=onNewSOS(load);return()=>{a();b();c()}},[]);
 const open=(x)=>{setSelected(x);setTeamIds((x.assignedRescueTeams||[]).map(t=>String(t._id||t)).filter(Boolean))};
 const assign=async()=>{if(!teamIds.length||!selected)return;try{await assignRescueTeam(selected._id||selected.id,teamIds);setSelected(null);setTeamIds([]);await load()}catch(e){setError(e?.response?.data?.message||e.message)}};
 const filtered=filter==="All"?requests:requests.filter(x=>x.severity===filter);
 return <div><PageHeader title="SOS Requests" subtitle={`${requests.length} live requests`} action={<div className="flex gap-2 flex-wrap">{["All","Critical","High","Medium","Low"].map(f=><button key={f} onClick={()=>setFilter(f)} className={`px-3 py-1.5 rounded-full text-xs font-semibold border ${filter===f?'bg-[#18352a] text-white':'border-[#dbeadb]'}`}>{f}</button>)}</div>}/>
 {error&&<div className="mb-4 bg-red-50 border border-red-200 text-red-700 rounded-xl p-3 text-sm">{error}</div>}
 <div className="bg-white border border-[#dbeadb] rounded-2xl overflow-auto"><table className="w-full text-sm"><thead><tr className="text-left text-slate-500 border-b"><th className="p-4">SOS</th><th className="p-4">Citizen</th><th className="p-4">Emergency</th><th className="p-4">Severity</th><th className="p-4">Status</th><th className="p-4">Rescue Teams / Distance</th></tr></thead><tbody>{filtered.map(x=><tr key={x._id||x.id} onClick={()=>open(x)} className="border-b hover:bg-slate-50 cursor-pointer"><td className="p-4 font-bold">#{String(x._id||x.id).slice(-8)}</td><td className="p-4">{x.user?.name||x.citizen?.name||"Citizen"}</td><td className="p-4">{x.disasterType}</td><td className="p-4">{x.severity}</td><td className="p-4"><span className={`px-2.5 py-1 rounded-full text-xs font-bold ${styles[x.status]||'bg-slate-100'}`}>{x.status}</span></td><td className="p-4">{(x.assignedRescueTeams||[]).length? <div className="space-y-1">{(x.assignedRescueTeams||[]).map(t=>{const tm=teams.find(q=>String(q._id)===String(t._id||t));const d=distanceKm(x.location,tm?.location);return <div key={t._id||t} className="text-xs"><b>🚑 {t.name||tm?.name||'Team'}</b> — {distanceText(d)}</div>})}</div>:"Unassigned"}</td></tr>)}</tbody></table></div>
 {selected&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4" onClick={()=>setSelected(null)}><div className="bg-white rounded-2xl p-6 w-full max-w-xl max-h-[90vh] overflow-auto" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><div><h3 className="text-lg font-extrabold">SOS #{String(selected._id||selected.id).slice(-8)}</h3><p className="text-xs text-slate-500 mt-1">Select one or more teams. Each team will see this SOS and its live distance.</p></div><button onClick={()=>setSelected(null)}>×</button></div><div className="mt-4 text-sm space-y-2"><p>Emergency: <b>{selected.disasterType}</b> · <b>{selected.severity}</b></p><p>Citizen: <b>{selected.user?.name||"—"}</b></p><p>Description: <b>{selected.description||"No description"}</b></p><p>Location: <b>{selected.location?.latitude?.toFixed?.(5)}, {selected.location?.longitude?.toFixed?.(5)}</b></p></div><div className="mt-5 space-y-2">{teams.map(t=>{const d=distanceKm(selected.location,t.location);const checked=teamIds.includes(String(t._id));return <label key={t._id} className={`flex items-center justify-between gap-3 rounded-xl border p-3 cursor-pointer ${checked?'border-green-500 bg-green-50':'border-slate-200'}`}><span className="flex items-center gap-3"><input type="checkbox" checked={checked} onChange={()=>setTeamIds(v=>checked?v.filter(id=>id!==String(t._id)):[...v,String(t._id)])}/><span><b>🚑 {t.name}</b><span className="block text-xs text-slate-500">{t.status} · {t.leaderName||'No leader'} · {t.lat&&t.lng?'GPS live':'GPS offline'}</span></span></span><b className="text-xs text-blue-700">{distanceText(d)}</b></label>})}</div><button onClick={assign} disabled={!teamIds.length} className="mt-5 w-full py-3 rounded-xl bg-[#18352a] text-white font-bold disabled:opacity-50">Assign {teamIds.length} Team{teamIds.length===1?'':'s'} to SOS</button></div></div>}</div>
}
