import React, { useEffect, useState } from "react";
import PageHeader from "../components/PageHeader";
import { trackMyRescueTeam } from "../services/api";
import { joinSOSRoom, leaveSOSRoom, onRescueLocationUpdate, onRescueStatusUpdate } from "../services/socket";
import { MapContainer, TileLayer, Marker, Popup, Polyline, CircleMarker } from "react-leaflet";
import L from "leaflet";
import "leaflet/dist/leaflet.css";

const teamIcon=L.divIcon({html:"<div style='font-size:28px'>🚑</div>",className:"",iconSize:[32,32],iconAnchor:[16,16]});
const citizenIcon=L.divIcon({html:"<div style='font-size:28px'>📍</div>",className:"",iconSize:[32,32],iconAnchor:[16,16]});
export default function TrackRescueTeam(){
 const [data,setData]=useState(null);const [error,setError]=useState("");
 const load=()=>trackMyRescueTeam().then(setData).catch(e=>setError(e?.response?.data?.message||"No rescue team is currently assigned."));
 useEffect(()=>{load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{const id=data?.sos?._id;if(!id)return;joinSOSRoom(id);const a=onRescueLocationUpdate(u=>{if(String(u.sosId)!==String(id))return;setData(d=>d?({...d,team:{...d.team,location:{latitude:u.lat,longitude:u.lng},lastUpdated:u.lastUpdated},distanceKm:u.lat!=null?undefined:d.distanceKm}):d);load()});const b=onRescueStatusUpdate(u=>{if(String(u.sosId)!==String(id))return;setData(d=>d?({...d,sos:{...d.sos,status:u.status,reachedAt:u.reachedAt}}):d)});return()=>{a();b();leaveSOSRoom(id)}},[data?.sos?._id]);
 const loc=data?.team?.location; const citizen=data?.sos?.location; const center=loc?[loc.latitude,loc.longitude]:citizen?[citizen.latitude,citizen.longitude]:[28.66,77.35];
 return <div><PageHeader title="Track Rescue Team" subtitle="Live location, distance, ETA and rescue status."/>{error?<div className="bg-white border border-red-200 rounded-2xl p-6 text-red-700">{error}</div>:!data?<div className="bg-white rounded-2xl p-6">Loading live rescue information...</div>:<div className="grid lg:grid-cols-3 gap-5"><div className="lg:col-span-2 bg-white rounded-2xl border overflow-hidden" style={{height:520}}><MapContainer center={center} zoom={13} style={{height:"100%"}}><TileLayer attribution="© OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{citizen&&<Marker position={[citizen.latitude,citizen.longitude]} icon={citizenIcon}><Popup>Your SOS location</Popup></Marker>}{loc&&<Marker position={[loc.latitude,loc.longitude]} icon={teamIcon}><Popup>{data.team.name}<br/>Last update: {data.team.lastUpdated?new Date(data.team.lastUpdated).toLocaleTimeString():"now"}</Popup></Marker>}{citizen&&loc&&<Polyline positions={[[citizen.latitude,citizen.longitude],[loc.latitude,loc.longitude]]}/>}</MapContainer></div><div className="bg-white rounded-2xl border border-[#dbeadb] p-6 space-y-4"><div><div className="text-xs text-slate-500">SOS STATUS</div><div className="text-2xl font-extrabold text-[#18352a]">{data.sos.status}</div></div><div className="border-t pt-4"><div className="text-xs text-slate-500">RESCUE TEAM</div><div className="text-lg font-bold">🚑 {data.team.name}</div><div className="text-sm text-slate-500">Leader: {data.team.leaderName}</div><div className="text-sm text-slate-500">Phone: {data.team.phone}</div></div><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-green-50 p-3"><div className="text-xs text-slate-500">Distance</div><div className="font-extrabold text-green-800">{data.distanceKm==null?"Updating...":`${data.distanceKm.toFixed(2)} km`}</div></div><div className="rounded-xl bg-blue-50 p-3"><div className="text-xs text-slate-500">ETA</div><div className="font-extrabold text-blue-800">{data.etaMinutes==null?"Updating...":`${data.etaMinutes} min`}</div></div></div><div className="rounded-xl bg-slate-50 p-4 text-sm">{data.sos.status==="Reached"?<b className="text-green-700">🟢 Rescue team has reached your location.</b>:data.sos.status==="Resolved"?<b className="text-green-700">✅ SOS resolved.</b>:<b>🚑 Rescue team is responding. Live GPS is active when the team device is online.</b>}</div><div className="text-xs text-slate-400">Last GPS update: {data.team.lastUpdated?new Date(data.team.lastUpdated).toLocaleString():"—"}</div></div></div>}</div>
}
